# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('tid', models.CharField(max_length=128)),
                ('cid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('time', models.CharField(max_length=128)),
                ('classroom', models.CharField(max_length=128)),
                ('price', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'coursesDB',
                'managed': False,
            },
        ),
    ]
